# Generated by Django 3.1.2 on 2021-04-13 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_title', models.CharField(max_length=300)),
                ('service_time', models.TimeField()),
                ('service_text', models.TextField()),
                ('post_image', models.ImageField(upload_to='service_images/')),
            ],
        ),
    ]
