# Generated by Django 3.1.2 on 2021-04-15 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20210413_0858'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_date', models.DateField(help_text='Day of the event', verbose_name='Day of the event')),
                ('schedule_timefrom', models.TimeField(help_text='Starting time', verbose_name='Starting time')),
                ('schedule_timeto', models.TimeField(help_text='Final time', verbose_name='Final time')),
                ('schedule_waiting_status', models.BooleanField(default=True)),
                ('schedule_notes', models.TextField(blank=True, help_text='Textual Notes', null=True, verbose_name='Textual Notes')),
            ],
            options={
                'verbose_name': 'Scheduling',
                'verbose_name_plural': 'Scheduling',
            },
        ),
    ]
