# Generated by Django 3.1.2 on 2021-04-20 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_auto_20210420_0904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='schedule_notes',
            field=models.TextField(default='Свободно', help_text='Textual Notes', verbose_name='Textual Notes'),
        ),
    ]
