# Generated by Django 3.1.2 on 2021-04-20 16:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('services', '0010_auto_20210420_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='schedule_notes',
            field=models.CharField(blank=True, default='free', help_text='Textual Notes', max_length=300),
        ),
        migrations.CreateModel(
            name='ServiceBooking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_comment', models.CharField(blank=True, default='Свободно', help_text='Textual Notes', max_length=300)),
                ('booking_date', models.DateTimeField()),
                ('schedule_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.schedule')),
                ('service_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.service')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
