# Generated by Django 3.1.2 on 2021-04-23 07:40

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0011_auto_20210420_1954'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicebooking',
            name='booking_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(default='79996450924', max_length=128, region=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, help_text='+79998887766', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='servicebooking',
            name='booking_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
