# Generated by Django 3.1.2 on 2021-04-23 07:52

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0013_remove_servicebooking_booking_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, default='79996450924', help_text='79998887766', max_length=128, null=True, region='RU'),
        ),
    ]
