# Generated by Django 3.1.2 on 2021-04-23 07:56

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0014_auto_20210423_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicebooking',
            name='booking_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, default='79996450924', help_text='79998887766', max_length=128, null=True, region='RU'),
        ),
    ]
