# Generated by Django 3.1.2 on 2021-04-27 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0015_servicebooking_booking_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicebooking',
            name='booking_phone',
            field=models.CharField(help_text='79998887766', max_length=12, null=True),
        ),
    ]
