# Generated by Django 3.1.2 on 2021-04-27 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0016_auto_20210427_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(help_text='+79998887766', max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='servicebooking',
            name='booking_phone',
            field=models.CharField(help_text='+79998887766', max_length=12, null=True),
        ),
    ]
