# Generated by Django 3.1.2 on 2021-05-17 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0017_auto_20210427_2029'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='service_price',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=19),
        ),
    ]
