# Generated by Django 3.1.2 on 2021-05-19 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0018_service_service_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='service_price',
            field=models.TextField(),
        ),
    ]
