# Generated by Django 3.1.2 on 2021-05-22 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0019_auto_20210519_1626'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicebooking',
            options={'ordering': ['-pk']},
        ),
        migrations.AlterField(
            model_name='service',
            name='service_price',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=19),
        ),
        migrations.AlterField(
            model_name='servicebooking',
            name='booking_phone',
            field=models.CharField(help_text='+79998887766', max_length=12, null=True, verbose_name='Телефон для записи'),
        ),
        migrations.AlterField(
            model_name='servicebooking',
            name='schedule_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.schedule', verbose_name='Дата и время записи'),
        ),
        migrations.AlterField(
            model_name='servicebooking',
            name='service_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.service', verbose_name='Услуга'),
        ),
    ]
